[colors]
foreground = "#cdccce"
background = "#140e1a"
cursor_bg = "#e0def4"
cursor_border = "#e0def4"
cursor_fg = "#140e1a"
selection_bg = "#3d375e"
selection_fg = "#cdccce"

ansi = [
  "#140e1a", # Black
  "#ff6767", # Red
  "#8effd9", # Green
  "#ffca85", # Yellow
  "#f477ff", # Blue
  "#61ffca", # Magenta
  "#a277ff", # Cyan
  "#cdccce", # White
]

brights = [
  "#2d2d2d", # Bright Black (Gray)
  "#ffca85", # Bright Red
  "#a277ff", # Bright Green
  "#ffca85", # Bright Yellow
  "#a277ff", # Bright Blue
  "#61ffca", # Bright Magenta
  "#61ffca", # Bright Cyan
  "#edecee", # Bright White
]

[metadata]
name = "baskin-pine"
author = "Adapted for WezTerm"
